meshblu:
  restart: always
  image: idcfchannel/meshblu
  volumes:
    - ./meshblu:/var/www
    - ./docker:/etc/supervisor/conf.d
    - /etc/localtime:/etc/localtime:ro
  environment:
#    - DEBUG=meshblu:mqtt,ascoltatori:redis,ascoltatori:mqtt,meshblu:sendMessage,meshblu:doMessageForward,meshblu:message-io-socket-handler,meshblu:createMessageIOEmitter,meshblu:MessageIOClient,meshblu:protocol:socketLogic
    - MONGODB_URI=mongodb://mongo:27017/skynet
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - UUID=idcf
    - TOKEN=channel
  ports:
    - "1883:1883"
  links:
    - redis
    - mongo
openresty:
  restart: always
  image: tenstartups/openresty
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx/conf:/etc/nginx
    - ./nginx/lua:/usr/local/openresty/nginx/lua
    - /etc/localtime:/etc/localtime:ro
  links:
    - redis
    - meshblu
  entrypoint: ["nginx", "-c", "/etc/nginx/nginx.conf"]
redis:
  restart: always
  image: redis
  volumes:
    - ./redis:/data
    - /etc/localtime:/etc/localtime:ro
mongo:
  restart: always
  image: mongo
  volumes:
    - ./mongo:/data/db
    - /etc/localtime:/etc/localtime:ro
rediscli:
  image: redis
  links:
    - redis
iotutil:
  image: idcfchannel/iotutil
  volumes:
    - /etc/localtime:/etc/localtime:ro
  links:
    - redis
    - openresty
    - meshblu
  environment:
    - MESHBLU_URL=http://meshblu/
  entrypoint: ["npm", "start"]
freeboard:
  build: ./freeboard
  volumes:
    - /etc/localtime:/etc/localtime:ro
  ports:
    - 8088:8080
bme280:
  build: ./bme280
  volumes:
    - /etc/localtime:/etc/localtime:ro
sensortag:
  build: ./sensortag
  volumes:
    - /etc/localtime:/etc/localtime:ro
manage:
  build: ./manage
  volumes:
    - /etc/localtime:/etc/localtime:ro
  ports:
    - "3030:3000"
managedev:
  build: ./managedev
  volumes:
    - ./managedev:/app
    - /etc/localtime:/etc/localtime:ro
  ports:
    - "3030:3000"
