meshblu:
  restart: always
  build: ./meshblu
#  image: octoblu/meshblu:0c3e5bd
  volumes:
    - ./meshblu:/var/www
    - ./docker:/etc/supervisor/conf.d
  environment:
    - DEBUG=meshblu:model:device,meshblu:register,meshblu:mqtt
    - MQTT_PORT=1883
    - MQTT_PASSWORD=skynetpass
    - MONGODB_URI=mongodb://mongo:27017/skynet
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  ports:
    - "1883:1883"
  links:
    - redis
    - mongo
openresty:
  restart: always
  image: tenstartups/openresty
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx/conf:/etc/nginx
    - ./nginx/lua:/usr/local/openresty/nginx/lua
  links:
    - redis
    - meshblu
  entrypoint: ["nginx", "-c", "/etc/nginx/nginx.conf"]
redis:
  restart: always
  image: redis
  volumes:
    - ./redis:/data
mongo:
  restart: always
  image: mongo
  volumes:
    - ./mongo:/data/db
rediscli:
  image: redis
  links:
    - redis
iotutil:
  build: ./iotutil
  volumes:
    - ./iotutil:/app
  links:
    - redis
    - openresty
  environment: 
    - MESHBLU_URL=https://openresty/
